### ISSUE TITLE
gulp-scss is not working for me

### ISSUE THREAD

**Issue by dilipkumar2k6** [Forumouth/gulp-scss#11]
I am trying to switch from gulp-sass to gulp-scss however surprisinly its not working for me. I have checkedin my code in following Git Hub.

https://github.com/dilipkumar2k6/gulp-sass

"gulp sass" is working because its using gulp-sass module. However "gulp scss" is not working because its using "gulp-scss".

Can you please help.
Thanks,
Dilip

**Comment by hiroaki-yamamoto** [comment]
https://www.ruby-lang.org/
https://rubygems.org/
http://bundler.io/
http://bundler.io/#getting-started
http://bundler.io/gemfile.html
http://bundler.io/bundle_install.html
http://bundler.io/man/bundle-exec.1.html

https://github.com/Forumouth/gulp-scss#optionsbundleexec-boolean-default-false

**Comment by dilipkumar2k6** [comment]
Do  I need to install bundleExec? I don't want to install anything else.  Can I use this without using Ruby?

**Comment by hiroaki-yamamoto** [comment]
> Do  I need to install bundleExec?

[bundler](http://bundler.io/), not [bundleExec](https://github.com/forumouth/gulp-scss#optionsbundleexec-boolean-default-false)
[bundler is written in ruby](https://github.com/bundler/bundler), and enabling [bundleExec](https://github.com/forumouth/gulp-scss#optionsbundleexec-boolean-default-false), this plugin needs [bundler](http://bundler.io/).

> I don't want to install anything else.

[Docker](https://www.docker.com/) prpvides a solution of this.

> Can I use this without using Ruby?

[Sass is written in ruby](https://github.com/sass/sass). Therefore you can do it as long as you create ruby interpreter like [this](https://github.com/ruby/ruby).

[gulp-sass](https://github.com/dlmanning/gulp-sass) is a wrapper of  [node-sass](https://github.com/sass/node-sass), and [node-sass](https://github.com/sass/node-sass) is a wrapper of [libsass](https://github.com/sass/libsass) that doesn't fully support the latest sass features.

**Comment by hiroaki-yamamoto** [comment]
Seems to be resolved
