### ISSUE TITLE
Never processes inputs with Gulp

### ISSUE THREAD

**Issue by legacybass** [Forumouth/gulp-scss#20]
Running a simple gulp script with the following outputs no files:

``` javascript
return gulp.src(['Styles/**/*.sass', 'Styles/**/*.scss'], { base: '.' })
.pipe(sass())
.pipe(gulp.dest('.'))
```

Putting `gulp-debug` before the `sass` call shows all my files, putting it after the `sass` call shows nothing. Something seems to be preventing gulp-scss from passing the files back through the stream and onto the `gulp.dest` call.

**Comment by hiroaki-yamamoto** [comment]
Hi :smiley:

As far as I read that code, the style sheets should be in `Styles/(some subdir)`. For example, if we have `Styles/sass/test.sass` and `Styles/scss/test.scss`, the path of the output in this case should be `Styles/sass/test.css` and `Styles/scss/test.css`.

Could you please make sure the outputs are there?

**Comment by legacybass** [comment]
That's where I'd expect the output to be, yes. However, there is no output. No files are generated anywhere in the tree structure. I've done a search all the way back to the root of the drive, and those files are never generated. I don't know that it makes any difference, but I was originally running this with Node 0.10, and have now upgraded to Node 4.0. With both versions, the result is the same. I also receive no errors or notifications that anything went wrong. The output in the console gives the appearance that everything went perfectly.

**Comment by hiroaki-yamamoto** [comment]
Hmm... it's weird. What OS are you using (e.g. OS X, Debian, Arch Linux, Windows 8, etc...)?

**Comment by legacybass** [comment]
I'm running Windows 10 Professional x64; however, this also happens on another machine running Windows 8 professional. Other than that, though, the script really is as simple as the example I gave. Nothing OS specific in my code.

**Comment by hiroaki-yamamoto** [comment]
I don't think [nodejs](https://nodejs.org/en/) supports windows well. As far as I tested on ArchLinux and Ubuntu, it ran good.

Could you use gulp-scss on Linux?

**Comment by legacybass** [comment]
Node has support Windows for a while, and even has support from Microsoft themselves. I've been using Node to create websites and run gulp scripts for years with no issues, so I _highly_ doubt that's the issue. I only ran into this because I usually use Less instead of Scss/Sass. In fact, IBM announced yesterday that they bought StrongLoop (the organization supporting Node), and plan to use it with their server business -- something they wouldn't have done if it didn't support Windows well.  I do have a Linux VM I can run, but given we develop on and for Windows, that doesn't do us any good.
If your plugin doesn't run on Windows, that's one thing; but it's certainly not because of node.

**Comment by hiroaki-yamamoto** [comment]
Okay, I show you the proof that this plugin runs on Linux.

[Travis](https://travis-ci.org/), a famous Continuous Integration System, is watching this repo and when I push commits / create PRs, it tries to run unit and integration tests. As you can see tests directory, there are 14 unit tests and 4 integration tests. In addition to this, there is `travis.yml`, which is called "Specific Domain Language" that specifies what I want the CI to do:

```
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - "gem install bundler"

before_script:
  - "bundle install --path=./vendor/bundle"
```

And, according to [Travis Documentation](http://docs.travis-ci.com/user/languages/javascript-with-nodejs/), `npm test` is executed as a default test script:

`package.json`

```
{
  "name": "gulp-scss",
  "version": "1.2.0",
  "description": "Gulp plugin for sass stylesheet compiler by standard approach",
  "main": "lib/scss.js",
  "scripts": {
    "test": "gulp unit-test integration-test"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/forumouth/gulp-scss.git"
  },
  "keywords": [
    "gulpplugin",
    "gulp-scss",
    "gulp-sass"
  ],
  "author": "Hiroaki Yamamoto <admin@hysoftware.net>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/forumouth/gulp-scss/issues"
  },
  "homepage": "https://github.com/forumouth/gulp-scss#readme",
  "devDependencies": {
    "chai": "^3.2.0",
    "coffee-script": "^1.9.2",
    "gulp": "^3.8.11",
    "gulp-coffee": "^2.3.1",
    "gulp-coffeelint": "^0.5.0",
    "gulp-mocha": "^2.0.1",
    "gulp-notify": "^2.2.0",
    "gulp-plumber": "^1.0.0",
    "gulp-sourcemaps": "^1.5.2",
    "mocha": "^2.2.4",
    "sinon": "^1.14.1"
  },
  "dependencies": {
    "convert-source-map": "^1.1.0",
    "dargs": "^4.0.1",
    "deepcopy": "^0.5.0",
    "gulp-util": "^3.0.4",
    "merge": "^1.2.0",
    "mkdirp": "^0.5.0",
    "node-kissdi": "^1.0.3",
    "q": "^1.3.0",
    "through2": "^2.0.0",
    "vinyl-sourcemaps-apply": "^0.1.4"
  }
}
```

Therefore, the result from the CI is: [![Build Status](https://travis-ci.org/Forumouth/gulp-scss.svg?branch=1.2.0)](https://travis-ci.org/Forumouth/gulp-scss), which means... you know.

Anyway, somehow there seem to be many users who use this plugin on Windows and it seems to be time to consider Windows.

**Comment by robertsimmons** [comment]
Just ran into this same issue yesterday, using a fresh install of the latest gulp-scss. Legacybass, did you ever get this to work on Windows?

**Comment by legacybass** [comment]
Sadly, no. Even after the latest commits which were supposed to support Windows, it still has the same behavior. I switched over to [gulp-sass](https://www.npmjs.com/package/gulp-sass) and it seems to work with no issues.

**Comment by robertsimmons** [comment]
Thanks for the response. I got confusing errors with the first attempt at gulp-sass, and gave up for the day. I'll give it another run and focus on it.

**Comment by legacybass** [comment]
I believe I did as well at first, which is why I tried this library. I got it working shortly after moving back, though. Now, I occasionally see that the libSass library needs to be rebuilt, but that's it. Running `npm rebuild` fixes it (although, the message usually says it didn't need the rebuild). I haven't seen the error after upgrading npm to > 3, however.

**Comment by hiroaki-yamamoto** [comment]
Hi guys :)

Did you have [sass](http://sass-lang.com/) installed? Until 1.3.16, error code was not handled as coded [there](https://github.com/Forumouth/gulp-scss/blob/1.3.16/src/scss.coffee). If not, could you try to install it?
