### ISSUE TITLE
Error: Compilation failed.: The command exited with code:127  Stack Trace: undefined

### ISSUE THREAD

**Issue by shibiaoz** [Forumouth/gulp-scss#30]
## error msg

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Compilation failed.: The command exited with code:127

Stack Trace:
undefined
```

gulp global version:

```
[00:36:20] CLI version 3.9.1
[00:36:20] Local version 3.9.1
```

gulp version is ^3.9.0

gulp-scss version

```
gulp-scss
^1.3.15
```

**Comment by hiroaki-yamamoto** [comment]
Hi,

Code 127 means a specified command_file could not be found by a non-interactive shell. Did you have sass and its dependencies installed on your system? If you didn't, please try installing them. You can find ruby code at https://github.com/ruby/ruby.

**Comment by hiroaki-yamamoto** [comment]
Anyway, this is already known and you don't seem to have sass installed on your sever. To fix the problem, install ruby and sass.
