### ISSUE TITLE
Could not locate Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by nidzovito** [Forumouth/gulp-scss#31]
I defined gulp task like this
var scss = require("gulp-scss");

gulp.task("scss", function () {
  gulp.src(
    "assets/stylesheets/hauls.scss"
  ).pipe(scss(
    {"bundleExec": true}
  )).pipe(gulp.dest("assets/stylesheets/hauls.css"));
});

But it says 
[10:14:14] Starting 'scss'...
[10:14:14] Finished 'scss' after 16 ms
Could not locate Gemfile or .bundle/ directory

**Comment by hiroaki-yamamoto** [comment]
Hi,
Did you have `scss` with `bundler --path ./vendor/bundle` installed on your app?

**Comment by nidzovito** [comment]
it is not ruby on rails project, it is node / html project so I don't have vendor folder

**Comment by hiroaki-yamamoto** [comment]
Well, this script needs scss that is written in Ruby and therefore, you need to install ruby and bundler as global dependencies. In addition to the dependencies, you will need to install scss with bundler as an app dependency, that means, you will need Gemfile like this:

``` Ruby
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "sass"
```

I'm not sure if [gulp-sass](https://www.npmjs.com/package/gulp-sass) supports compass, but if you don't need compass, I recommend to use [gulp-sass](https://www.npmjs.com/package/gulp-sass)

**Comment by nidzovito** [comment]
when i use gulp-sass it works.
